### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Borwe** [dm1try/golden_size#6]
Came about this from a reddit post, was wondering on how you did you created tests? Any links you can sudgest to learn more about testing neovim plugins?

**Comment by dm1try** [comment]
Neovim "functional" testing environment is used here. Overview can be found [here](https://github.com/KillTheMule/KillTheMule.github.io/blob/master/test_plugins_from_neovim.md).
Basically, you need an installed Neovim version locally and then you run `TEST_FILE=/plugin_path/pluging_spec.lua make functionaltest` from Neovim directory(see [example](https://github.com/dm1try/golden_size/blob/master/.github/workflows/main.yml#L25)) .

Such solution has own pros and cons, but I like Lua and the ability to use a large number of testing helpers provided by Neovim.

**Comment by Borwe** [comment]
Thanks.
